### ISSUE TITLE
File not found error when using the action

### ISSUE THREAD

**Issue by bdubaut** [agyemanjp/ci-checks-action#7]
Hi,

I'm trying to use this action to annotate a workflow run with linter errors on my project. Everything seems to be working fine, except that when I get to the step that runs the annotation action, I get this error:
```
##[error]File not found: '/home/runner/work/_actions/prmph/ci-checks-action/1.0.1/dist/index.js'
```

The project is an Elixir project, here is the job yaml:
```yaml
lint:
    name: Credo linter
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.10.4' # Define the elixir version [required]
          otp-version: '22.3' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - uses: actions/download-artifact@v2
        with:
          name: _build
          path: ./_build
      - run: mix credo --strict --format=json > credo_results.json # output is put in the JSON file here
      - name: Annotate PR
        uses: prmph/ci-checks-action@1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          checks: "lint:credo_results.json" # calling the checks on the file
```

Am I doing something wrong?

**Comment by bdubaut** [comment]
In case the problem comes from the results file format, here is an example of a file with one linter offense found:
```json
{
  "issues": [
    {
      "category": "readability",
      "check": "Credo.Check.Readability.ModuleDoc",
      "column": 11,
      "column_end": 20,
      "filename": "apps/test_credo/lib/test_credo.ex",
      "line_no": 1,
      "message": "Modules should have a @moduledoc tag.",
      "priority": 1,
      "trigger": "TestCredo"
    }
  ]
}
```

If there is no offenses, the file looks like this:
```json
{
  "issues": []
}
```

**Comment by agyemanjp** [comment]
Thanks for the report. A new version that should fix all these issue was published a few days ago. Please use that version like so:
```
- name: Annotate Checks
        uses: **agyemanjp/ci-checks-action@1.0.2**
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          checks: "lint:.lint-report.json|test:.test-report.json"

```
